CREATE TABLE `user_pressure`
(
    `id`          bigint(20)                        NOT NULL AUTO_INCREMENT COMMENT 'id',
    `name`        varchar(64) CHARACTER SET utf8mb4 NOT NULL DEFAULT '' COMMENT '姓名',
    `name_enc`    varchar(100)                               DEFAULT NULL COMMENT '姓名（密文）',
    `sex`         varchar(16) CHARACTER SET utf8mb4          DEFAULT NULL COMMENT '性别',
    `age`         int(255)                                   DEFAULT NULL COMMENT '年龄',
    `create_time` datetime                          NOT NULL COMMENT '创建时间',
    `update_time` datetime                          NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `status`      int(10)                           NOT NULL DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status1`     int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status2`     int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status3`     int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status4`     int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status5`     int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status6`     int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status7`     int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status8`     int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status9`     int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status10`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status11`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status12`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status13`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status14`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status15`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status16`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status17`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status18`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status19`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status20`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status21`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status22`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status23`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status24`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status25`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status26`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status27`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status28`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status29`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status30`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status31`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status32`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status33`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status34`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status35`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status36`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status37`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status38`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status39`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status40`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status41`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status42`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status43`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status44`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status45`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status46`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status47`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status48`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status49`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status50`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status51`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status52`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status53`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status54`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status55`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status56`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status57`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status58`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status59`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status60`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status61`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status62`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status63`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status64`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status65`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status66`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status67`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status68`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status69`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status70`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status71`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status72`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status73`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status74`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status75`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status76`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status77`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status78`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status79`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status80`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status81`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status82`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status83`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status84`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status85`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status86`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status87`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status88`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status89`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status90`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status91`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status92`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status93`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status94`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status95`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status96`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status97`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status98`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status99`    int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    `status100`   int(10)                                    DEFAULT '0' COMMENT '是否删除 1删除 0未删除',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 302
  DEFAULT CHARSET = utf8 COMMENT ='用户表';

